name: Claude PR Assistant (Gitea)

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  claude-code-action:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
      issues: read
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Run Claude PR Action
        uses: anthropics/claude-code-action@beta
        with:
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          timeout_minutes: "60"
          use_gitea: "true"
          gitea_host: ${{ secrets.GITEA_HOST }}
          gitea_token: ${{ secrets.GITEA_TOKEN }}
          platform: "gitea"
        env:
          USE_GITEA: "true"
          GITEA_SERVER_URL: ${{ secrets.GITEA_HOST }}
          GITEA_API_URL: ${{ secrets.GITEA_API_URL }}
          GITEA_ACCESS_TOKEN: ${{ secrets.GITEA_TOKEN }}
